os: linux
sudo: required
language: java
python:
  - "2.7"

services:
  - docker

env:
  DOCKER_COMPSE_VERSION: 1.14.0
  DOCKER_VERSION: 17.06.0-ce

before_install:
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install --force-yes docker-ce=${DOCKER_VERSION}
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker build -t master master/
  - docker container run -d -p 127.0.0.1:80:80 --name master master
  - docker container ls | grep -q master

before_script:
  - pip install pytest requests

script:
  - docker info
  - pytest
